version: "3"
services:
  directus:
    image: directus/directus:10.10.4
    container_name: directus_server
    ports:
      - 8055:8055
    volumes:
      - ./Directus/database:/directus/database
      - ./Directus/uploads:/directus/uploads
      - ./Directus/extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3
  chatapi:
    build: ./RealTimeChatAPI
    container_name: chatapi
    ports:
      - 4000:4000
    volumes:
      - "./RealTimeChatAPI:/RealTimeChatAPI"
      - "/RealTimeChatAPI/node_modules"
    depends_on:
      directus:
        condition: service_healthy
        restart: true